#!/bin/sh

/bin/mount -t proc proc /proc

# the default "vt102" is crap.
export TERM=linux
#
# reset colors, to not hurt my eyes...
echo -e "\033[0m"
# 132 lines
echo -e "\033[?3h"

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do
	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue
	case "$i" in
	*.sh)
		# Source shell script for speed.
		(
			trap - INT QUIT TSTP
			set start
			. $i
		)
		;;
	*)
		# No sh extension, so fork subprocess.
		$i start
		;;
	esac
done
